// Product metadata — single source of truth for SEO, JSON-LD, llms.txt, ml.yaml
export const product = {
  name: 'Bifrost',
  tagline: 'One API for every model.',
  subline: 'Bifrost optimizes every request.',
  description: 'Intelligent AI execution layer that routes, optimizes, caches, validates, and recovers AI requests across multiple model providers.',
  longDescription: 'Bifrost is an intelligent AI execution layer that understands, optimizes, routes, executes, validates, and recovers AI requests across multiple model providers. Through a single OpenAI-compatible API, it compresses context, selects optimal routes, uses available quota, survives failures, and explains every decision.',
  website: 'https://bifrost.omixsystems.store',
  apiBase: 'https://bifrost.omixsystems.store/v1',
  github: 'https://github.com/twistedoliver211fs-art/bifrost',
  version: '0.1.0',
  author: {
    name: 'OMIX Digital Solutions',
    url: 'https://omixsystems.store',
    email: 'omixsystems@gmail.com',
    location: 'Kericho, Kenya',
  },
  pipeline: ['REQUEST', 'UNDERSTAND', 'OPTIMIZE', 'CACHE', 'PREDICT', 'ROUTE', 'EXECUTE', 'VALIDATE', 'RECOVER', 'OBSERVE', 'LEARN'],
  features: [
    { id: 'route', title: 'Route', description: 'Automatically select the best model, provider, and account for every request based on capability, cost, latency, and health.' },
    { id: 'optimize', title: 'Optimize', description: 'Compress prompts, tool output, and context before paying for unnecessary tokens. Deduplicate, normalize, and prune.' },
    { id: 'cache', title: 'Cache', description: 'Reuse previous work through exact match and semantic similarity caching. Never pay for the same inference twice.' },
    { id: 'recover', title: 'Recover', description: 'Automatic retry, failover, circuit breaking, and self-healing. Your app stays up when providers go down.' },
    { id: 'control', title: 'Control', description: 'Enforce policies, budgets, quotas, data residency, tenant isolation, and provider restrictions at the gateway layer.' },
    { id: 'observe', title: 'Observe', description: 'Trace every routing decision, token usage, fallback event, cost attribution, and provider health in real time.' },
  ],
  providers: [
    { name: 'OpenAI', models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'] },
    { name: 'Anthropic', models: ['claude-sonnet-4', 'claude-opus-4'] },
    { name: 'Google', models: ['gemini-2.5-pro', 'gemini-2.5-flash'] },
    { name: 'Mistral', models: ['mistral-large', 'mistral-small'] },
    { name: 'Groq', models: ['llama-3.3-70b', 'mixtral-8x7b'] },
    { name: 'Cerebras', models: ['llama-3.3-70b', 'llama-3.1-8b'] },
    { name: 'SambaNova', models: ['llama-3.3-70b', 'deepseek-r1'] },
    { name: 'OpenRouter', models: ['llama-3.3-70b:free', 'qwen-2.5-72b:free'] },
    { name: 'Cloudflare', models: ['llama-3.3-70b', 'llama-3.1-8b'] },
    { name: 'HuggingFace', models: ['llama-3.3-70b', 'qwen-2.5-72b'] },
    { name: 'Ollama Cloud', models: ['gemma4:31b', 'gpt-oss:20b'] },
    { name: 'DeepSeek', models: ['deepseek-v4-flash', 'deepseek-v3'] },
  ],
  capabilities: [
    'Automatic Fallback',
    'Circuit Breakers',
    'Provider Cooldowns',
    'Self-Healing',
    'Backpressure',
    'Priority Queues',
    'Stream Keepalive',
    'Multi-Account Rotation',
    'Prompt Compression',
    'Tool Output Compression',
    'Semantic Cache',
    'Recoverable Context',
    'Context Dependency Graph',
    'Context Garbage Collection',
    'Policy-as-Code',
    'Tenant Isolation',
    'Data Residency',
    'Budget Enforcement',
  ],
} as const;
