// Re-export all workspace packages for Vercel compatibility
// Vercel pnpm doesn't create workspace symlinks, so we use relative imports
// and re-export from a single location that all API routes can import from.

export { createSeedRegistry, type ModelRegistry } from '../../packages/models/src/index';
export {
  ProviderRegistry,
  createOllamaProvider, createOpenAiProvider, createZenProvider,
  createOllamaCloudProvider, createBytezProvider, createGeminiProvider,
  createGroqProvider, createCerebrasProvider, createSambaNovaProvider,
  createOpenRouterProvider, createCloudflareProvider, createMistralProvider,
  createHuggingFaceProvider, createVercelGatewayProvider,
  type ProviderAdapter,
  type NormalizedRequest,
  type NormalizedMessage,
  type NormalizedResponse,
  type NormalizedStreamEvent,
  type ProviderCapabilities,
  type ProviderError,
} from '../../packages/providers/src/index';
export {
  PolicyEngine,
  PolicyRegistry,
  PolicySimulator,
  TenantManager,
  tenantManager,
  DataResidencyEngine,
  residencyEngine,
  setProviderRegion,
  getProviderRegion,
  setResidencyAuditLogger,
  type Policy,
  type PolicyDecision,
  type PolicyContext,
  type TenantConfig,
  type DataResidencyConfig,
  type SimulationResult,
  type PolicyMatch,
  type PolicyConstraints,
  type PolicyRequires,
  type PolicyPreference,
  type PolicyFallback,
  type PolicyOptimization,
  type RoutingPreferences,
  type CompressionBehavior,
  type CacheConfig,
  type CostLimits,
  type ProviderAccess,
  type QualityTargets,
  type RegionMetadata,
  type ResidencyDecision,
  type QualityPreference,
  type CostPreference,
  type LatencyPreference,
  type PolicyVersion,
} from '../../packages/policy/src/index';
export {
  route,
  buildCandidates,
  DEFAULT_ROUTING_STRATEGY,
  DEFAULT_STRATEGY_WEIGHTS,
  type RoutingMode,
  type RoutingStrategy,
  type HardConstraints,
  type RoutingCandidate,
  type RoutingDecision,
  type RoutingScores,
  type CandidateBuildOptions,
} from '../../packages/router/src/index';
export {
  CompressionEngine,
  analyzeRequest,
  detectBoilerplate,
  canonicalizePrompt,
  compressStructural,
  deduplicateContext,
  pruneContext,
  compressToolOutput,
  type CompressionResult,
  type CompressionLevel,
  type CompressionConfig,
  type TokenAnalysis,
  type CompressionPass,
  type ContextItem,
  type BoilerplateRule,
  type SafetyClassification,
  type CanonicalOperation,
} from '../../packages/compression/src/index';
export {
  CacheEngine,
  InMemoryCacheStore,
  DEFAULT_CACHE_POLICY,
  createCachePolicy,
  createTenantCachePolicy,
  createModelCachePolicy,
  normalizeRequest,
  exactFingerprint,
  semanticFingerprint,
  type CachePolicy,
  type CacheEntry,
  type CacheHit,
  type CacheEngineConfig,
  type CacheEngineStats,
  type SemanticFingerprintConfig,
} from '../../packages/cache/src/index';
export {
  CircuitBreaker,
  ProviderCooldown,
  AutoFallback,
  SelfHealing,
  BackpressureEngine,
  StreamKeepalive,
  MultiAccountRotation,
  PriorityQueue,
  ExecutionEngine,
  type CircuitState,
  type CooldownReason,
  type Priority,
  type ProviderErrorCategory,
  type CircuitBreakerConfig,
  type CircuitBreakerEntry,
  type CircuitBreakerMetrics,
  type CooldownConfig,
  type CooldownEntry,
  type FallbackConfig,
  type FallbackStrategy,
  type HealthState,
  type HealthThresholds,
  type HealthRecord,
  type ConcurrencyConfig,
  type TokenBucket,
  type SlotConfig,
  type PriorityQueueEntry,
  type BackpressureConfig,
  type StreamKeepaliveConfig,
  type StreamSession,
  type AccountConfig,
  type AccountHealth,
  type QueuePolicy,
  type QueuedRequest,
  type ReliabilityConfig,
  type ExecutionResult,
  type ReleaseFn,
  type ExecutionRequest,
  type ExecutionOptions,
} from '../../packages/reliability/src/index';
export {
  createTrace,
  finalizeTrace,
  addSpan,
  startSpan,
  endSpan,
  addSpanEvent,
  exportTrace,
  exportTraces,
  generateTraceId,
  generateSpanId,
  calculateScore,
  DEFAULT_SCORE_WEIGHTS,
  shouldShadow,
  executeShadow,
  computeComparison,
  consumeShadowBudget,
  resetShadowBudget,
  createDataset,
  runBenchmark,
  compareBenchmarks,
  simulate,
  compareWithBaseline,
  getTrace,
  listTraces,
  getAggregatedScores,
  getShadowComparisonResults,
  getBenchmarkById,
  getBenchmarkResultsByDataset,
  listBenchmarkDatasets,
  runWhatIfSimulation,
  insertRequestTrace,
  insertTraceSpan,
  insertOptimizerScore,
  insertShadowResult,
  insertBenchmarkDataset,
  insertBenchmarkResult,
  insertWhatIfSimulation,
  getRequestTraces,
  getTraceSpans,
  getOptimizerScores,
  getShadowResults,
  getBenchmarkDataset,
  getBenchmarkResults,
  getWhatIfSimulations,
  type RequestTrace,
  type Span,
  type SpanEvent,
  type ScoreComponent,
  type OptimizerScore,
  type ShadowConfig,
  type ShadowResult,
  type BenchmarkDataset,
  type BenchmarkConfig,
  type BenchmarkResult,
  type WhatIfConfig,
  type WhatIfResult,
  type DashboardFilters,
} from '../../packages/observability/src/index';
